version: '3'

services:
  zk1:
    image: zookeeper
    restart: always
    hostname: zk1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk2:
    image: zookeeper
    restart: always
    hostname: zk2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk3:
    image: zookeeper
    restart: always
    hostname: zk3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
  master:
    image: dkv
    command: "master -port=8111 -zk='zk1:2181,zk2:2181,zk3:2181' -schema='zk'"
    build: .
    depends_on: 
      - zk1
      - zk2
      - zk3
  client:
    image: dkv
    ports:
      - 8080:8080
    command: "client -port=8080 -zk='zk1:2181,zk2:2181,zk3:2181' -masters=1"
    depends_on: 
      - zk1
      - zk2
      - zk3
  client1:
    image: dkv
    ports:
      - 8081:8080
    command: "client -port=8080 -zk='zk1:2181,zk2:2181,zk3:2181' -masters=1"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica00:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=0 -gid=100 -masters=1 -schema='zk' -isr=2 -debug=false"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica01:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=1 -gid=100 -masters=1 -schema='zk' -isr=2 -debug=false"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica02:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=2 -gid=100 -masters=1 -schema='zk' -isr=2 -debug=false"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica10:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=0 -gid=101 -masters=1 -schema='zk' -isr=2 -debug=false"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica11:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=1 -gid=101 -masters=1 -schema='zk' -isr=2 -debug=false"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica12:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=2 -gid=101 -masters=1 -schema='zk' -isr=2 -debug=false"
    depends_on: 
      - zk1
      - zk2
      - zk3
