version: '3'

services:
  zk1:
    image: myzk
    restart: always
    hostname: zk1
    build:
      ./docker/myzk
    volumes:
    - "./docker/myzk/conf:/zookeeper/conf"
    - "./docker/myzk/data1:/data"
  zk2:
    image: myzk
    restart: always
    hostname: zk2
    volumes:
      - "./docker/myzk/conf:/zookeeper/conf"
      - "./docker/myzk/data2:/data"
  zk3:
    image: myzk
    restart: always
    hostname: zk3
    volumes:
      - "./docker/myzk/conf:/zookeeper/conf"
      - "./docker/myzk/data3:/data"
  master:
    image: dkv
    command: "master -port=8111 -zk='zk1:2181,zk2:2181,zk3:2181' -schema='zk'"
    build: .
    depends_on: 
      - zk1
      - zk2
      - zk3
  client:
    image: dkv
    ports:
      - 8080:8080
    command: "client -port=8080 -zk='zk1:2181,zk2:2181,zk3:2181' -masters=1"
    depends_on: 
      - zk1
      - zk2
      - zk3
  client1:
    image: dkv
    ports:
    - 8081:8080
    command: "client -port=8080 -zk='zk1:2181,zk2:2182,zk3:2181' -masters=1"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica00:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=0 -gid=100 -masters=1"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica01:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=1 -gid=100 -masters=1"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica02:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=2 -gid=100 -masters=1"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica10:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=0 -gid=101 -masters=1"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica11:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=1 -gid=101 -masters=1"
    depends_on: 
      - zk1
      - zk2
      - zk3
  replica12:
    image: dkv
    command: "replica -port=9111 -zk='zk1:2181,zk2:2181,zk3:2181' -peers=3 -me=2 -gid=101 -masters=1"
    depends_on: 
      - zk1
      - zk2
      - zk3
